---
version : '3.9'

services:
  db:
    container_name: chat_gpt_db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - chat_gpt_db_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      timeout: 3s
      retries: 10
      interval: 3s
    networks:
      - chat_gpt



  api:
    container_name: api
    image: vladimirbodrin/chat:tagname
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 8087:8087

    networks:
      - chat_gpt

networks:
  chat_gpt:
    driver: bridge

volumes :
  chat_gpt_db_pg_data:
